{
 "title": "Nexus",
 "tags": [
  "service",
  "consul.build"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "_bucket",
    "label": "Bucket",
    "query": "15s,30s,1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "_environment",
    "label": "Environment",
    "query": "SHOW TAG VALUES WITH KEY = \"environment\""
   }
  ]
 },
 "panels": [
  {
   "title": "JVM Garbage collector",
   "type": "graph",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Collections / s" }
   ],
   "targets": [
    {
     "alias": "Count ($tag_host)",
     "groupBy": [
      { "params": [ "$_bucket" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jvm_garbage_collector",
     "select": [
      [
       { "params": [ "CollectionCount" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "service", "operator": "=", "value": "nexus" },
      { "condition": "AND", "key": "environment", "operator": "=~", "value": "/^$_environment$/" }
     ]
    },
    {
     "alias": "Time ($tag_host)",
     "groupBy": [
      { "params": [ "$_bucket" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jvm_garbage_collector",
     "select": [
      [
       { "params": [ "CollectionTime" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "service", "operator": "=", "value": "nexus" },
      { "condition": "AND", "key": "environment", "operator": "=~", "value": "/^$_environment$/" }
     ]
    },
    {
     "alias": "Pending finalize ($tag_host)",
     "groupBy": [
      { "params": [ "$_bucket" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jvm_memory",
     "select": [
      [
       { "params": [ "ObjectPendingFinalizationCount" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "service", "operator": "=", "value": "nexus" },
      { "condition": "AND", "key": "environment", "operator": "=~", "value": "/^$_environment$/" }
     ]
    }
   ]
  },
  {
   "title": "JVM Memory Pool",
   "type": "graph",
   "gridPos": { "h": 9, "w": 14, "x": 10, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "Collection committed ($tag_host)",
     "groupBy": [
      { "params": [ "$_bucket" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jvm_memory_pool",
     "select": [
      [
       { "params": [ "CollectionUsage.committed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "service", "operator": "=", "value": "nexus" },
      { "condition": "AND", "key": "environment", "operator": "=~", "value": "/^$_environment$/" }
     ]
    },
    {
     "alias": "Collection used ($tag_host)",
     "groupBy": [
      { "params": [ "$_bucket" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jvm_memory_pool",
     "select": [
      [
       { "params": [ "CollectionUsage.used" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "service", "operator": "=", "value": "nexus" },
      { "condition": "AND", "key": "environment", "operator": "=~", "value": "/^$_environment$/" }
     ]
    },
    {
     "alias": "Peak committed ($tag_host)",
     "groupBy": [
      { "params": [ "$_bucket" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jvm_memory_pool",
     "select": [
      [
       { "params": [ "PeakUsage.committed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "service", "operator": "=", "value": "nexus" },
      { "condition": "AND", "key": "environment", "operator": "=~", "value": "/^$_environment$/" }
     ]
    },
    {
     "alias": "Peak used ($tag_host)",
     "groupBy": [
      { "params": [ "$_bucket" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jvm_memory_pool",
     "select": [
      [
       { "params": [ "PeakUsage.used" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "service", "operator": "=", "value": "nexus" },
      { "condition": "AND", "key": "environment", "operator": "=~", "value": "/^$_environment$/" }
     ]
    },
    {
     "alias": "Usage committed ($tag_host)",
     "groupBy": [
      { "params": [ "$_bucket" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jvm_memory_pool",
     "select": [
      [
       { "params": [ "Usage.committed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "service", "operator": "=", "value": "nexus" },
      { "condition": "AND", "key": "environment", "operator": "=~", "value": "/^$_environment$/" }
     ]
    },
    {
     "alias": "Usage used ($tag_host)",
     "groupBy": [
      { "params": [ "$_bucket" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jvm_memory_pool",
     "select": [
      [
       { "params": [ "Usage.used" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "service", "operator": "=", "value": "nexus" },
      { "condition": "AND", "key": "environment", "operator": "=~", "value": "/^$_environment$/" }
     ]
    }
   ]
  },
  {
   "title": "JVM Heap memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 13, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "Committed ($tag_host)",
     "groupBy": [
      { "params": [ "$_bucket" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jvm_memory",
     "select": [
      [
       { "params": [ "HeapMemoryUsage.committed" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "service", "operator": "=", "value": "nexus" },
      { "condition": "AND", "key": "environment", "operator": "=~", "value": "/^$_environment$/" }
     ]
    },
    {
     "alias": "Max ($tag_host)",
     "groupBy": [
      { "params": [ "$_bucket" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jvm_memory",
     "select": [
      [
       { "params": [ "HeapMemoryUsage.max" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "service", "operator": "=", "value": "nexus" },
      { "condition": "AND", "key": "environment", "operator": "=~", "value": "/^$_environment$/" }
     ]
    },
    {
     "alias": "Used ($tag_host)",
     "groupBy": [
      { "params": [ "$_bucket" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jvm_memory",
     "select": [
      [
       { "params": [ "HeapMemoryUsage.used" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "service", "operator": "=", "value": "nexus" },
      { "condition": "AND", "key": "environment", "operator": "=~", "value": "/^$_environment$/" }
     ]
    }
   ]
  },
  {
   "title": "JVM non-Heap memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 11, "x": 13, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "Committed ($tag_host)",
     "groupBy": [
      { "params": [ "$_bucket" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jvm_memory",
     "select": [
      [
       { "params": [ "NonHeapMemoryUsage.committed" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "service", "operator": "=", "value": "nexus" },
      { "condition": "AND", "key": "environment", "operator": "=~", "value": "/^$_environment$/" }
     ]
    },
    {
     "alias": "Init ($tag_host)",
     "groupBy": [
      { "params": [ "$_bucket" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jvm_memory",
     "select": [
      [
       { "params": [ "NonHeapMemoryUsage.init" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "service", "operator": "=", "value": "nexus" },
      { "condition": "AND", "key": "environment", "operator": "=~", "value": "/^$_environment$/" }
     ]
    },
    {
     "alias": "Used ($tag_host)",
     "groupBy": [
      { "params": [ "$_bucket" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jvm_memory",
     "select": [
      [
       { "params": [ "NonHeapMemoryUsage.used" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "service", "operator": "=", "value": "nexus" },
      { "condition": "AND", "key": "environment", "operator": "=~", "value": "/^$_environment$/" }
     ]
    }
   ]
  },
  {
   "title": "Host CPU",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "user ($tag_host)",
     "groupBy": [
      { "params": [ "$_bucket" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_user" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "category", "operator": "=", "value": "artefacts" },
      { "condition": "AND", "key": "environment", "operator": "=~", "value": "/^$_environment$/" }
     ]
    },
    {
     "alias": "system ($tag_host)",
     "groupBy": [
      { "params": [ "$_bucket" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_system" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "category", "operator": "=", "value": "artefacts" },
      { "condition": "AND", "key": "environment", "operator": "=~", "value": "/^$_environment$/" }
     ]
    },
    {
     "alias": "iowait ($tag_host)",
     "groupBy": [
      { "params": [ "$_bucket" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_iowait" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "category", "operator": "=", "value": "artefacts" },
      { "condition": "AND", "key": "environment", "operator": "=~", "value": "/^$_environment$/" }
     ]
    }
   ]
  },
  {
   "title": "Host memory % used",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$_bucket" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mem",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "category", "operator": "=", "value": "artefacts" },
      { "condition": "AND", "key": "environment", "operator": "=~", "value": "/^$_environment$/" }
     ]
    }
   ]
  }
 ]
}